### ISSUE TITLE
Monkey's Audio (ape) tag data can crash guayadeque (inside TagLib)

### ISSUE THREAD

**Issue by RomanHargrave** [anonbeat/guayadeque#40]
```
09:39:17 PM: Doing Library Update in /home/roman/.local/mnt/music_ro/

Thread 5 "guayadeque" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe137a700 (LWP 14347)]
0x00007ffff3ca4b71 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff3ca4b71 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff4def2cc in TagLib::String::toCString(bool) const () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#2  0x0000555555814cd1 in Guayadeque::guTagInfo::ReadExtendedTags(TagLib::APE::Tag*) ()
#3  0x0000555555815a53 in Guayadeque::guApeTagInfo::Read() ()
#4  0x000055555577b517 in Guayadeque::guDbLibrary::ReadFileTags(wxString const&, bool) ()
#5  0x0000555555736955 in Guayadeque::guLibUpdateThread::Entry() ()
#6  0x00007ffff7af9dc2 in wxThread::CallEntry() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007ffff7b02453 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#8  0x00007ffff3456424 in start_thread (arg=0x7fffe137a700) at pthread_create.c:333
#9  0x00007ffff31999bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

The TagLib release log mentions that such an issue may have been fixed in 1.11, which is definitely the version with which Guayadeque was built. My guess is that TagLib expects Guayadeque to perform some manner of checks on files before reading them with TagLib. 

VLC had a similar issue and solved it in-tree: https://trac.videolan.org/vlc/ticket/7036

**Comment by anonbeat** [comment]
Please can you email me or put somewhere a file that causes the problem ? I checked the one posted on the vlc bug and doesnt crash guayadeque...
